image: maven:latest
stages:
- build
- test
- deploy


build:
  stage: build
  script:
    - mvn compile
  artifacts:
    paths:
      - target

test:
  stage: test
  script:
    - mvn test

pages:
  image: maven:latest
  stage: deploy
  script:
      - mvn javadoc:javadoc
      - ls 
  artifacts:
    paths:
      - public
  only:
    - master
