image: maven:latest

build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target

test:
  stage: test
  script:
    - java -jar target/hello-1.0.0.jar

pages:
  image: maven:slim
  stage: deploy
  script:
    - curl https://tech.utugit.fi/soft/tools/sitegen/sitegen.jar -o sitegen.jar
    - java -jar sitegen.jar -docs -download -commits
  artifacts:
    paths:
      - public
  only:
    - master
